name: "Dev Skydera Preview Deploy Action"
description: "Get started with Python Container actions"
author: "Lecole Cole"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
